apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: kamalaklar/myapp:bd96e92437199b9e6788e9af89c07c902d3a20bd
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: myapp-configmap-test