apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: bdemirpolat/myapp:12e87a60a390d5ad5488feaee42c78e6b4d7e9a3
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: myapp-configmap