apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: kamalaklar/hello:0.0.1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: myapp-configmap