apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: bdemirpolat/myapp:2a110d29c38d45b30af78f54046aafed41f34478
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: myapp-configmap