apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: kamalaklar/myapp:e4656e71764fcef215a9bc80456b70e1b548dd2c
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: myapp-configmap