name: ci

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: bdemirpolat/myapp:${{ github.sha }}
      - uses: actions/checkout@v2
      - run: |
          perl -i -pe 's/myapp:.*/myapp:${{ github.sha }}/g' argocd/deployment.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add argocd/deployment.yaml
          git commit -m "generated"
          git push
