name: ci

on:
  push:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kamalaklar/hello:${{ github.sha }}

      - name: Change deployment.yaml and commit
        run: perl -i -pe 's/{IMAGE_TEST}/${{ github.sha }}/g' argocd/deployment.yaml
      
      - name: Commit and Push
        run: git add argocd/deployment.yaml | git commit -m "change deployment.yaml" | git push origin master